version: '2'
services:
  helio-rest:
    image: acimmino/helio-rest:latest
    volumes: 
      - type: volume
        source: helio-db
        target: /helio/app
        volume: {}
    ports:
      - "4567:4567"
    networks:
      - helio

  frontend:
    image: emiliocrespoperan/helio-frontend:latest
    depends_on:
      - helio-rest
    ports:
      - "4201:80"
    networks:
      - helio

  playground:
    image: emiliocrespoperan/helio-frontend-playground:latest
    depends_on:
      - helio-rest
    ports:
      - "4202:80"
    networks:
      - helio
      

networks:
  helio:
  
volumes:
  helio-db:
    name: helio-db